### ISSUE TITLE
[Suggestion] Prepare to deal with `sailfishos/ssu` PR #16

### ISSUE THREAD

**Issue by nephros** [sailfishos-chum/sailfishos-chum-gui-installer#39]
#### DESCRIPTION

An unannounced and unreleased Sailfish OS version ("4.6") will change the way versions are handled in the `ssu` utility.

I imagine this may have an impact on how Installer handles/must handle OBS repository information, hence this issue.

#### ADDITIONAL INFORMATION

- https://github.com/sailfishos/ssu/pull/16
- https://irclogs.sailfishos.org/logs/%23sailfishos/%23sailfishos.2024-04-11.log.html

**Comment by Olf0** [comment]
See also https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/270, https://github.com/storeman-developers/harbour-storeman-installer/issues/308 and https://github.com/storeman-developers/harbour-storeman/issues/488.

Please use https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/270 as the main, tracking issue for this.

**Comment by Olf0** [comment]
Should be closed by PR #40.
